---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: sensu-server
    data_bags_path: data_bags
    driver:
      network:
        - ["private_network", {ip: "192.168.17.51"}]
      customize:
        cpus: 1
        memory: 2048
    run_list:
      - recipe[sensu-test::server]
    attributes:
  - name: sensu-client
    data_bags_path: data_bags
    driver:
      network:
        - ["private_network", {ip: "192.168.17.52"}]
      customize:
        cpus: 1
        memory: 2048
    run_list:
      - recipe[sensu-test::client]
    attributes:
