name             'sensu-test'
maintainer       'Daniel Klopp'
maintainer_email 'dsklopp@gmail.com'
license          'All rights reserved'
description      'Installs/Configures sensu-test'
long_description 'Installs/Configures sensu-test'
version          '0.1.0'

depends 'sensu'
depends 'uchiwa'
